"""add user_id to tasks

Revision ID: 9445168437e3
Revises: 6695dd976d24
Create Date: 2026-07-13 11:15:47.850368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9445168437e3'
down_revision = '6695dd976d24'
branch_labels = None
depends_on = None


def upgrade():
    # Modified automated migration script as follows to prevent db crash:
    # 1. Add the column (allowing NULLs temporarily)
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=True))

    # 2. Backfill the data (Using Postgres-native UPDATE...FROM syntax)
    op.execute(
        """
        UPDATE tasks 
        SET author_id = lists.author_id 
        FROM lists 
        WHERE tasks.parent_list_id = lists.id
        """
    )

    # 3. Lock down to NOT NULL
    op.alter_column('tasks', 'author_id', existing_type=sa.Integer(), nullable=False)

    # 4. Create the named Foreign Key constraint
    op.create_foreign_key(
        'fk_tasks_users_author_id',
        'tasks',
        'users',
        ['author_id'],
        ['id'],
        ondelete='CASCADE'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
